version: "{build}"

os:
  - Visual Studio 2017
  - Visual Studio 2015
  - Visual Studio 2013

environment:
    matrix:
        - additional_flags: ""
          wmain: 0

# Win32 and x64 are CMake-compatible solution platform names.
# This allows us to pass %PLATFORM% to CMake -A.
platform:
  - Win32
  - x64

# Build Configurations, i.e. Debug, Release, etc.
configuration:
  - Debug
  - Release

# Cmake will autodetect the compiler, but we set the arch
before_build:
  - set CXXFLAGS=%additional_flags%
  - cmake -H. -BBuild -A%PLATFORM% -DUI_CXX_USE_QT=OFF

# Build with MSBuild
build:
  project: Build\spirit.sln # path to Visual Studio solution or project
  parallel: true                 # enable MSBuild parallel builds
  verbosity: normal              # MSBuild verbosity level {quiet|minimal|normal|detailed}

test_script:
  - cd Build
  - ctest -V -R -j2 -C %CONFIGURATION%